services:

  ## ###############
  ## Sendy
  ## ###############
  sendy_apache:
    container_name: sendy_apache
    build:
      args:
        - SENDY_LICENSE_KEY=${SENDY_LICENSE_KEY}
        - CACHEBUST=${CACHEBUST}
    depends_on:
      - sendy_mysql
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./sendy/config.php:/var/www/html/includes/config.php
      - ./sendy/uploads:/var/www/html/uploads
      - ./sendy/apache2.conf:/etc/apache2/apache2.conf
    networks:
      - internal-in-no-external-out
      - internal-in-external-out
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 30s

  sendy_mysql:
    container_name: sendy_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${SENDY_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: sendy_mail
      MYSQL_USER: sendyuser
      MYSQL_PASSWORD: ${SENDY_MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
      - ./database-imports:/docker-entrypoint-initdb.d
    networks:
      - internal-in-no-external-out
    restart: unless-stopped
  
  # Cron manager for sendy
  sendy_crontab:
    container_name: sendy_crontab
    build:
      args:
        - SENDY_LICENSE_KEY=${SENDY_LICENSE_KEY}
        - CACHEBUST=${CACHEBUST}
    command: [ "cron", "-f", "/etc/cron.d/sendy_cronjobs" ]
    healthcheck:
      test: ["CMD", "cat", "~/cron-timestamp.txt"]
      interval: 60m
      timeout: 10s
      retries: 60
      start_period: 120s
    depends_on:
      - sendy_mysql
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./sendy/config.php:/var/www/html/includes/config.php
      - ./sendy/uploads:/var/www/html/uploads
      - ./sendy/apache2.conf:/etc/apache2/apache2.conf
    networks:
      - internal-in-no-external-out
      - internal-in-external-out
    restart: unless-stopped